### ISSUE TITLE
 ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

### ISSUE THREAD

**Issue by Zhang-Jack** [pushpendughosh/Stock-market-forecasting#2]
Hi, 
when I tried to porting this project into python notebook for Google colab, 
I subjected to this issue below:
----------------------------------------
1993
----------------------------------------
(251416, 244) (121079, 244) 97.39196372032166
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 240, 1)]          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 25)                2700      
_________________________________________________________________
dropout (Dropout)            (None, 25)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 52        
=================================================================
Total params: 2,752
Trainable params: 2,752
Non-trainable params: 0
_________________________________________________________________
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-e5d28dba8b31> in <module>()
    253     print(train_data.shape,test_data.shape,time.time()-start)
    254 
--> 255     model,predictions = trainer(train_data,test_data)
    256     returns = simulate(test_data,predictions)
    257     returns.to_csv(result_folder+'/avg_daily_rets-'+str(test_year)+'.csv')

12 frames
<ipython-input-16-e5d28dba8b31> in trainer(train_data, test_data, model_type)
    148               validation_split=0.2,
    149               callbacks=callbacks,
--> 150               batch_size=512
    151               )
    152 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    795           data_adapter.train_validation_split((x, y, sample_weight),
    796                                               validation_split=validation_split,
--> 797                                               shuffle=False))
    798 
    799     with self.distribute_strategy.scope(), \

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in train_validation_split(arrays, validation_split, shuffle)
   1336 
   1337   train_arrays = nest.map_structure(
-> 1338       functools.partial(_split, indices=train_indices), arrays)
   1339   val_arrays = nest.map_structure(
   1340       functools.partial(_split, indices=val_indices), arrays)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    615 
    616   return pack_sequence_as(
--> 617       structure[0], [func(*x) for x in entries],
    618       expand_composites=expand_composites)
    619 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    615 
    616   return pack_sequence_as(
--> 617       structure[0], [func(*x) for x in entries],
    618       expand_composites=expand_composites)
    619 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _split(t, indices)
   1332     if t is None:
   1333       return t
-> 1334     t = ops.convert_to_tensor_v2(t)
   1335     return array_ops.gather_v2(t, indices)
   1336 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1281       name=name,
   1282       preferred_dtype=dtype_hint,
-> 1283       as_ref=False)
   1284 
   1285 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1339 
   1340     if ret is None:
-> 1341       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1342 
   1343     if ret is NotImplemented:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
     50 def _default_conversion_function(value, dtype, name, as_ref):
     51   del as_ref  # Unused.
---> 52   return constant_op.constant(value, dtype, name=name)
     53 
     54 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name)
    260   """
    261   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 262                         allow_broadcast=True)
    263 
    264 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    268   ctx = context.context()
    269   if ctx.executing_eagerly():
--> 270     t = convert_to_eager_tensor(value, ctx, dtype)
    271     if shape is None:
    272       return t

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     94       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     95   ctx.ensure_initialized()
---> 96   return ops.EagerTensor(value, ctx.device_name, dtype)
     97 
     98 

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

**Comment by pushpendughosh** [comment]
Can you please check which tensorflow version you are using?
`import tensorflow as tf`
`print(tf.__version__)`

**Comment by pushpendughosh** [comment]
I do not know if it will serve the issue you are getting, but I think you need to depreciate the tensorflow version. 
`!pip install scikit-learn==0.20.4`
`!pip install tensorflow==1.14.0`
Taking that as a note, I can re-write my codes so that it works on higher tensorflow versions also. Let me know if the issue still persists.

**Comment by Zhang-Jack** [comment]
2.2.0

**Comment by Zhang-Jack** [comment]
OK, after downgrade tensorflow and scikit-learn, it works now! Thank you for your help, pushpendughosh!

**Comment by pushpendughosh** [comment]
Awesome, so I close this issue. Let me know if you have any issues further.
